### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by kastork** [ibmrcruicks/multipass-docker-engine#1]
Thanks for this nice alternative to Docker Desktop and easy instructions.

FWIW, on my macOS Catalina machine, it did not work to set `DOCKER_HOST=<ip>` as you describe in the README, I had to put the entire connection string, like `DOCKER_HOST=tcp://<ip>:2375` before my docker cli or lazydocker would make the connection  from the mac side.

My docker cli and lazydocker were installed on the mac side with homebrew

**Comment by ibmrcruicks** [comment]
thanks for the feedback, Kirk -- much appreciated.
I have updated the connection string format, as it work fine for Big Sur too
